import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowUpRight, Check, Clock3, ShieldCheck, Zap, ChevronRight } from 'lucide-react'
import BeforeAfter from '../components/BeforeAfter'
import FAQ from '../components/FAQ'
import type { FAQItem } from '../components/FAQ'
import { localPortfolioItems } from '../data/portfolio'
const MAP:Record<string,any>={
  'embroidery-digitizing':{title:'Embroidery Digitizing', what:'Digitizing converts your artwork into a stitch file embroidery machines read. Our Wilcom-certified specialists manually plot stitch direction, density, underlay, and pull compensation – so your sew is clean, minimal trims, zero gaps.', benefits:[{t:'Perfect Registration',d:'Push-pull compensation prevents gaps & overlaps on seams.'},{t:'Minimal Trims',d:'Smart sequencing cuts machine time & thread breaks.'},{t:'All Machine Formats',d:'DST, PES, JEF, EXP, EMB, CND – any 2 head to 20 head.'},{t:'Tricky Fabrics',d:'Small lettering <5mm, 3D puff, caps, towels – optimized.'}], process:[{s:'Upload Art',d:'PNG, JPG, PDF, AI – even photo of stitch.'},{s:'Manual Digitizing',d:'Senior Wilcom artist plots every stitch manually.'},{s:'Proof & Edit',d:'3D stitch preview + sew-out report. Free tweaks.'},{s:'Production File',d:'Final file + lifetime backup – ready to run.'}], pricing:'From $10 – bulk $08. Rush 2-4h. 100% free revisions.'},
  'vector-artwork':{title:'Vector Artwork', what:'Vector converts low-res raster to infinitely scalable AI, EPS, SVG. We redraw manually with pen tool – sharp nodes, perfect curves, Pantone matched. Never auto-trace.', benefits:[{t:'True Manual Vector',d:'Pen-tool rebuild – razor edges, clean nodes.'},{t:'Pantone Matched',d:'Spot colors + layered separations for screen print.'},{t:'Any Use',d:'Screen, DTG, embroidery, signage, cut vinyl presets.'},{t:'Same Day',d:'Most vectors in 6-12h with unlimited edits.'}], process:[{s:'Send Raster',d:'JPG, PNG – even blurry photo of shirt.'},{s:'Manual Redraw',d:'Illustrator expert rebuilds pixel-perfect.'},{s:'Unlimited Revisions',d:'Tweak until razor perfect – no extra fee.'},{s:'Vector Delivery',d:'AI, EPS, SVG, PDF, CDR – all included.'}], pricing:'From $15 per design – unlimited revisions, no hidden fees.'},
  'custom-patches':{title:'Custom Patches', what:'Custom patches 50 pcs to 10k – embroidered 75% coverage, woven fine detail, PVC, chenille, leather – any shape, merrowed or laser cut border, 50+ backing options.', benefits:[{t:'All Patch Types',d:'Embroidered, woven, PVC, leather, chenille.'},{t:'Any Backing',d:'Iron-on, velcro, peel-stick, sew-on, magnetic.'},{t:'Bulk Pricing',d:'$5 @100pcs down to $3 @1000+.'},{t:'Free Mockup',d:'Digital proof + physical sample option – before pay.'}], process:[{s:'Design & Quote',d:'Upload art – mockup + pricing same day.'},{s:'Approve Mockup',d:'Front mockup with backing & border choice.'},{s:'Production',d:'7-12 day production, rush 5 days.'},{s:'Ship Worldwide',d:'Quality check + tracked shipping.'}], pricing:'From $5/ pc at 100 pcs. $3 @1000+. Free mockup.'},
  'dtf-dtg-sheets':{title:'DTF & DTG Sheets', what:'We build 22x24” gang sheets for DTF film – color corrected ICC, channels merged, white underbase tuned, ready to press. No ghosting, no color shift, maximum designs per sheet.', benefits:[{t:'Color Corrected ICC',d:'Print-accurate – matches DTF film RIP.'},{t:'300 DPI Crisp',d:'High DPI – no pixelation on press.'},{t:'Gang Optimized',d:'Max designs per sheet – save on transfers.'},{t:'Weed Lines Removed',d:'Cut paths cleaned – ready to press.'}], process:[{s:'Send Logos',d:'PNG, AI, multiple files for one gang sheet.'},{s:'We Layout',d:'We arrange + color correct + white base.'},{s:'PDF Proof',d:'Dimensions & qty proof for approval.'},{s:'Ready PNG',d:'RIP-ready PNG for DTF printer.'}], pricing:'$0.35 to $1.13 per linear inch or $5.00 to $7.00 per linear foot, depending on the size, quantity, and print type – unlimited logos on sheet.'},
  'custom-hats':{title:'Custom Hats', what:'From digitizing to sample – structured, unstructured, trucker, snapback, bucket & beanie. 3D puff, flat, applique + patch combos with front/side/back photoreal mockups.', benefits:[{t:'Photoreal Mockups',d:'See your hat before production.'},{t:'Puff Expert',d:'Clean puff edges and controlled stitch density.'},{t:'Flexible Quantities',d:'Suitable for one-off artwork and repeat production.'},{t:'Cap Sequencing',d:'Center-out sequencing helps reduce puckering.'}], process:[{s:'Send Logo',d:'Any logo + hat style – we advise best fit.'},{s:'3D Mockup',d:'Front, side, back presentation.'},{s:'Digitize for Cap',d:'Hat-specific underlay and sequence.'},{s:'Production File',d:'Final files prepared for production.'}], pricing:'Custom quote based on artwork complexity and placement.'},
  'vehicle-graphics-wraps':{title:'Vehicle Graphics & Wraps', what:'Custom vehicle graphics for cars, vans, pickups and fleets — from logo placement and door graphics to full livery concepts and cut-ready vinyl artwork.', benefits:[{t:'Custom Livery',d:'Graphics built around the vehicle and brand.'},{t:'Print & Cut Ready',d:'Clean artwork for vinyl print and plotter workflows.'},{t:'Fleet Consistency',d:'Repeatable layouts for multiple vehicles.'},{t:'Mockup First',d:'Review the concept before production.'}], process:[{s:'Send Vehicle + Brand',d:'Share vehicle photos, measurements and logos.'},{s:'Concept Layout',d:'We build the visual direction and placements.'},{s:'Proof & Revise',d:'Review the mockup and request adjustments.'},{s:'Production Artwork',d:'Final print/cut artwork is prepared.'}], pricing:'Custom quote based on vehicle size, coverage and artwork complexity.'},
}
export default function ServiceDetail(){
  const {slug}=useParams(); const data=MAP[slug as string]
  const [portfolio,setPortfolio]=useState<any[]>([]); const [faqs,setFaqs]=useState<FAQItem[]>([])
  useEffect(()=>{
    if(!data){ document.title='Service not found'; return }
    document.title=`${data.title} – Brode Designz`; window.scrollTo(0,0)
    fetch(`/api/portfolio?service=${slug}`).then(r=>r.json()).then(d=>setPortfolio(Array.isArray(d)&&d.length ? d : localPortfolioItems.filter((x:any)=>x.service_type===data.title || x.category===data.title))).catch(()=>setPortfolio(localPortfolioItems.filter((x:any)=>x.service_type===data.title || x.category===data.title)))
    fetch('/api/faqs').then(r=>r.json()).then(setFaqs).catch(()=>{})
  },[slug,data])
  if(!data) return <div className="max-w-[1280px] mx-auto px-6 py-24">Service not found. <Link to="/services" className="text-blue-mid underline">All services</Link></div>
  return (
    <div>
      <section className="grad-brand-2 text-white relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(800px_at_80%_0%,rgba(79,195,247,0.22),transparent)]"/>
        <div className="relative max-w-[1280px] mx-auto px-6 py-12 md:py-20">
          <div className="flex items-center gap-2 text-[12px] text-white/55"><Link to="/" className="hover:text-white">Home</Link><ChevronRight className="w-3.5 h-3.5"/><Link to="/services" className="hover:text-white">Services</Link><ChevronRight className="w-3.5 h-3.5"/><span className="text-white font-medium">{data.title}</span></div>
          <h1 className="font-heading font-extrabold text-[34px] md:text-[56px] leading-[0.92] tracking-[-0.03em] text-white mt-6 max-w-3xl">{data.title}</h1>
          <p className="mt-4 text-white/70 max-w-2xl text-[15px] md:text-[17px] leading-7">Premium {data.title.toLowerCase()} crafted for apparel brands, embroidery shops & merch creators — fast, accurate, guaranteed quality.</p>
          <div className="mt-8 flex gap-3 flex-wrap"><Link to="/get-a-quote" className="h-12 px-7 rounded-full bg-white text-navy-dark font-bold text-[14px] inline-flex items-center gap-2">Get Quote for {data.title} <ArrowUpRight className="w-4 h-4"/></Link><Link to="/portfolio" className="h-12 px-7 rounded-full border border-white/20 text-white font-semibold text-[14px] inline-flex items-center gap-2 hover:bg-white/10">View Samples</Link></div>
        </div>
      </section>
      <section className="max-w-[1280px] mx-auto px-6 py-16 md:py-20 grid lg:grid-cols-2 gap-12 items-start">
        <div>
          <div className="inline-flex px-3 py-1 rounded-full bg-blue-pale text-blue-mid text-[11px] font-bold tracking-widest uppercase">What is {data.title}?</div>
          <h2 className="font-heading font-extrabold text-[26px] md:text-[34px] leading-[1.1] mt-4">{data.title} — Done Right, Not Rushed</h2>
          <p className="mt-4 text-[15px] leading-7 text-body">{data.what}</p>
          <div className="mt-8 grid grid-cols-3 gap-3">{[{k:'Avg Turn',v:'12h'},{k:'Revisions',v:'Free'},{k:'Accuracy',v:'99.2%'}].map(i=> <div key={i.k} className="rounded-[16px] bg-bg border border-black/5 p-4 text-center"><div className="font-heading font-extrabold text-[18px] text-navy-dark">{i.v}</div><div className="text-[10px] font-bold tracking-widest uppercase text-body-2 mt-1">{i.k}</div></div>)}</div>
        </div>
        <div className="rounded-[24px] border border-black/5 bg-white p-3 shadow-[0_16px_40px_rgba(10,26,51,0.08)]">
          <img src={slug === 'vehicle-graphics-wraps' ? '/portfolio/vehicle-wrap-neon.svg' : slug === 'custom-patches' ? '/portfolio/patch-badge-original.svg' : slug === 'custom-hats' ? '/portfolio/cap-3d.jpg' : slug === 'vector-artwork' ? '/portfolio/dragon.png' : '/portfolio/left-chest.jpg'} alt={data.title} className="rounded-[16px] w-full aspect-[4/3] object-contain bg-bg" loading="lazy" />
          <div className="mt-3 rounded-[14px] bg-navy-dark text-white p-4 flex items-center justify-between"><div><div className="text-[11px] uppercase tracking-widest text-white/50 font-bold">Quality Check</div><div className="font-heading font-bold text-[14px] mt-1 text-white">✓ Wilcom senior reviewed</div></div><div className="w-10 h-10 rounded-full bg-white/15 flex items-center justify-center">✓</div></div>
        </div>
      </section>
      <section className="bg-bg py-16 md:py-20 px-6 border-y border-black/[0.04]">
        <div className="max-w-[1280px] mx-auto"><h3 className="font-heading font-extrabold text-[24px] md:text-[34px] text-center">Benefits you actually feel on the machine</h3><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-10">{data.benefits.map((b:any,i:number)=><div key={i} className="bg-white rounded-[18px] p-7 border border-black/5"><div className="w-10 h-10 rounded-[12px] grad-brand text-white flex items-center justify-center"><Check className="w-5 h-5"/></div><h4 className="font-heading font-bold mt-5 text-[15px]">{b.t}</h4><p className="text-[13px] leading-6 text-body mt-1.5">{b.d}</p></div>)}</div></div>
      </section>
      <section className="py-16 md:py-20 px-6 max-w-[1280px] mx-auto">
        <h3 className="font-heading font-extrabold text-[24px] md:text-[34px] text-center">How it works — 4 simple steps</h3>
        <div className="grid md:grid-cols-4 gap-8 mt-12 relative">
          <div className="hidden md:block absolute top-[18px] left-[12%] right-[12%] h-[2px] bg-gradient-to-r from-navy-dark/15 via-blue-mid/20 to-blue-light/20"/>
          {data.process.map((p:any,i:number)=><div key={i} className="text-center relative"><div className="w-10 h-10 rounded-full grad-brand text-white font-extrabold flex items-center justify-center mx-auto shadow-lg ring-4 ring-white">{i+1}</div><h4 className="font-heading font-bold mt-4 text-[15px]">{p.s}</h4><p className="text-[13px] text-body leading-6 mt-1.5 max-w-[240px] mx-auto">{p.d}</p></div>)}
        </div>
      </section>
      <section className="bg-bg py-16 px-6 border-y border-black/[0.04]">
        <div className="max-w-[1280px] mx-auto"><div className="flex flex-wrap justify-between items-end gap-4 mb-8"><h3 className="font-heading font-extrabold text-[22px] md:text-[28px]">{data.title} samples — before / after</h3><Link to="/portfolio" className="text-[13px] font-bold text-blue-mid hover:text-navy-dark">View all →</Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{portfolio.slice(0,3).map((it:any)=><div key={it.id}>{it.before_image && it.after_image ? <BeforeAfter before={it.before_image} after={it.after_image} alt={it.title}/> : <div className="aspect-[4/3] rounded-[18px] bg-white border border-black/5 overflow-hidden p-3"><img src={it.image} alt={it.title} className="w-full h-full object-contain"/></div>}<div className="mt-3 font-heading font-bold text-[13.5px] text-navy-dark">{it.title}</div><div className="text-[12px] text-body">{it.description}</div></div>)}{portfolio.length===0 && <div className="col-span-3 text-center py-16 text-body text-[14px]">Samples loading…</div>}</div></div>
      </section>
      <section className="py-16 px-6 max-w-[1280px] mx-auto grid lg:grid-cols-2 gap-10">
        <div className="rounded-[24px] grad-brand-2 p-[1px]"><div className="rounded-[23px] bg-[#0A1933] p-8 md:p-10 text-white relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(500px_at_100%_0%,rgba(79,195,247,0.22),transparent)]"/><div className="relative"><h3 className="font-heading font-extrabold text-[24px] md:text-[28px] text-white leading-tight">Transparent pricing — no surprises</h3><p className="mt-3 text-white/65 text-[14px] leading-6">{data.pricing} Volume shops get dedicated monthly rates – ask.</p><ul className="mt-6 space-y-2.5 text-[13px] text-white/85"><li className="flex gap-2.5"><Zap className="w-4 h-4 text-blue-light flex-shrink-0"/> Rush 2-4h available for urgent orders</li><li className="flex gap-2.5"><ShieldCheck className="w-4 h-4 text-blue-light flex-shrink-0"/> 100% satisfaction guarantee – free fixes</li><li className="flex gap-2.5"><Clock3 className="w-4 h-4 text-blue-light flex-shrink-0"/> 24/7 human support – real artists</li></ul><Link to="/get-a-quote" className="mt-8 h-12 px-7 rounded-full bg-white text-navy-dark font-bold text-[14px] inline-flex items-center gap-2 hover:bg-blue-light transition">Get Your Quote — 2h Response <ArrowUpRight className="w-4 h-4"/></Link></div></div></div>
        <div><h3 className="font-heading font-bold text-[20px]">Related services</h3><div className="mt-4 space-y-3">{Object.entries(MAP).filter(([k])=>k!==slug).slice(0,3).map(([k,v]:any)=><Link key={k} to={`/services/${k}`} className="flex items-center justify-between p-4 rounded-[14px] border border-black/5 bg-white hover:border-blue-accent/30 hover:shadow-sm transition"><span className="font-heading font-semibold text-[14px] text-navy-dark">{v.title}</span><ArrowUpRight className="w-4 h-4 text-body"/></Link>)}</div><div className="mt-10"><h4 className="font-heading font-bold mb-4">{data.title} FAQ</h4><FAQ faqs={faqs.slice(0,3)} /></div></div>
      </section>
    </div>
  )
}
